### PR TITLE
AUR legacy: aliza-free, masterpdfeditor-free, typora-free

### PR DESCRIPTION
**Pull request by FabioLolix**
AUR pkgbuilds for proprietary programs which no longer have a free-to-use version, intentionally old version

### CODE REVIEW

**Comment by FabioLolix** [comment]
At first sight didn't seen that masterpdfeditor-free was already legacy in 800.renames-and-merges

**Comment by FabioLolix** [comment]
Also typora is already seen as legacy

**Comment by AMDmi3** [comment]
It's not AUR specific and can be handled in a better way, such as by setting `altscheme` on a version range (`verge`). This will lead to these project having two newest versions.

**Comment by FabioLolix** [comment]
> can be handled in a better way, such as by setting altscheme on a version range (verge)

Don't how to set that

I'm closing this since isn't great

**Comment by AMDmi3** [comment]
The required rules (for 900 ruleset) would look like:

`{ name: typora, verge: "1.0", altscheme: true } # paid since 1.0, so allow free version to be preserved`

On a second thought, as long as free versions are no longer released, this (for 220 ruleset) should go too and may be even better:

`{ name: typora, ver: "0.11.18", legacy: true } # last free version`

**Pull request closed without merging**
