### PR TITLE
Fix servarr stack versions

### PR DESCRIPTION
**Pull request by txtsd**
Hopefully this is mostly correct!

Is there a way to specify `LiGurOS Develop`?

### CODE REVIEW

**Comment by AMDmi3** [comment]
You don't need to specify liguros at all as gentoo covers it.

**Comment by txtsd** [comment]
Better?
There is no stable version of readarr. It's all develop. I don't suppose I need to do anything in that case?

**Comment by txtsd** [comment]
See: https://github.com/Readarr/Readarr/releases

It's only pre-releases, from the develop branch, and there are nightly builds from the azure CI.

**Comment by AMDmi3** [comment]
Oh. Then I'd consider https://github.com/Readarr/Readarr/releases official

**Pull request merged**
