### PR TITLE
Merge khronos-ocl-icd-loader

### PR DESCRIPTION
**Pull request by FabioLolix**
Hi, they are the same 

https://repology.org/projects/?search=khronos-ocl-icd&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=

### CODE REVIEW

**Comment by AMDmi3** [comment]
This looks misnamed in aur.

**Comment by FabioLolix** [comment]
I have contacted @sl1pkn07

**Comment by sl1pkn07** [comment]
Hi

when [Extra] repo renames their "ocl-icd" to "ocl-icd-loader"

greetings

**Comment by AMDmi3** [comment]
Nothing to do here

**Pull request closed without merging**
