### PR TITLE
Merge open-broadcaster-software in to obs-studio

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by AMDmi3** [comment]
The rule merges obs-studio into open-broadcaster-software. It should be the other way around.

**Comment by luzpaz** [comment]
Oh, thank you. I misunderstood the instructions https://github.com/repology/repology-rules#you-want-to-merge-differently-named-packages-into-a-single-entry  
`Add rule like - { setname: <new name>, name: <old name> }`  
the `new name` in my comprehension was to be the target name and the `old name` was the name to change :man_facepalming:

**Comment by AMDmi3** [comment]
> I misunderstood the instructions

I've changed that README line, does it look more clear now?

> Fix previous commit

Please fix sorting and preferably squash into a single commit.

**Comment by luzpaz** [comment]
> > I misunderstood the instructions
> 
> I've changed that README line, does it look more clear now?  

I don't see the change


> > Fix previous commit
> 
> Please fix sorting and preferably squash into a single commit.

Done.

**Comment by AMDmi3** [comment]
> I don't see the change

Sorry, just pushed it.

> Done.

It looks broken now.

**Comment by luzpaz** [comment]
> ..Sorry, just pushed it.

:+1: Thank you.
 
> It looks broken now.

I realized that it didn't need a new entry since there was a pre-exisiting one. So i tacked it on.

**Comment by AMDmi3** [comment]
> I realized that it didn't need a new entry since there was a pre-exisiting one. So i tacked it on.

Oh I get it now. You need to use brackets here as it's now an array and not a single item. Like in the next rule.

**Comment by luzpaz** [comment]
Done (hopefully :blush:)

**Pull request merged**
