### PR TITLE
Add disambiguation for crane

### PR DESCRIPTION
**Pull request by Ikke**
Three distinct projects with the same name exist:

- https://github.com/michaelsauter/crane docker-compose like project
- https://github.com/ewilde/crane dotnet build tool
- https://github.com/google/go-containerregistry/tree/main/cmd/crane
  tool to interact with images and registries

### CODE REVIEW

**Review by AMDmi3 — CHANGES_REQUESTED** [review]
- There are 3 projects
- There needs to be a final `unclassified` rule
- Might be better to reuse exiting name for google crane, probably `go:containerregistry`

**Comment by Ikke** [comment]
@AMDmi3 Addressed your requested changes. Hope this is what you meant.

**Comment by Ikke** [comment]
@AMDmi3 ping

**Comment by AMDmi3** [comment]
Done, sorry for delay. Changed target names to more meaningful ones.

**Pull request merged**
