### PR TITLE
Ignore ver "0" and "deprecated" for vcpkg

### PR DESCRIPTION
**Pull request by dg0yt**
In vcpkg, use of version "0" indicates meta ports or ports which have been renamed.
Example: readline.

### CODE REVIEW

**Comment by dg0yt** [comment]
> Example: readline.

> These rules are useless and won't change any statuses. What are you trying to achieve?

I want version "0" of "readline" to be ignored for "vcpkg".
https://repology.org/projects/?search=readline&maintainer=&category=&inrepo=vcpkg&notinrepo=&repos=&families=&repos_newest=&families_newest=

**Comment by AMDmi3** [comment]
This will not ignore readline. You've probably meant `remove` instead. However at least `dbhhelp` is neither of a deprecated, renamed, or meta port, so version criteria is unreliable. It may be better to check in the parser that portfile.cmake only contains `set(VCPKG_POLICY_EMPTY_PACKAGE enabled)` and comments or something.

**Comment by dg0yt** [comment]
> However at least dbghelp is neither of a deprecated, renamed, or meta port, so version criteria is unreliable.

OTOH it doesn't really do much except for copying files out the Windows SDK. I could ask if they are willing to change to another value (date or just `1`).

> It may be better to check in the parser that portfile.cmake only contains `set(VCPKG_POLICY_EMPTY_PACKAGE enabled)` and comments or something.

This policy isn't really a good indicator. It can be used subject to `if()` guards, and it can be used even real ports such as `cmakerc` or  `coin-or-buildtools`.

**Comment by AMDmi3** [comment]
> OTOH it doesn't really do much except for copying files out the Windows SDK. I could ask if they are willing to change to another value (date or just 1).

This won't change a thing and I don't endorse no-op changes just for repologys sake.

> This policy isn't really a good indicator. It can be used subject to if() guards, and it can be used even real ports such as cmakerc or coin-or-buildtools.

That's unfortunate. Well I suggest we don't do anything here then. After merging readline flavors, `readline` metapackage is considered `legacy` so it won't affect outdated packages lists and statistics. Other metapackages may be handled similar way (or remain unique packages, or be renamed in 850 rulese in case of clashes with unrelated projects). I don't like hiding stuff based on unreliable criteria.

**Comment by dg0yt** [comment]
Thanks. Some things on the vpckg side are still a little bit immature. OTOH it is not always clear to me what is the desired resolution on the repology side, including where to draw the line between general pattern and specific rules.

**Pull request closed without merging**
