### PR TITLE
README: Clarify split-ambiguities instructions

### PR DESCRIPTION
**Pull request by waldyrious**
Also link to the list of conditions that can be used to disambiguate packages.

### CODE REVIEW

**Comment by AMDmi3** [comment]
I've updated these docs some more, please check.

**Comment by waldyrious** [comment]
> I've updated these docs some more, please check.

I appreciate the extra detail, but it doesn't seem to match the actual content of the files. For example, in [850.split-ambiguities/f.yaml](https://github.com/repology/repology-rules/blob/master/850.split-ambiguities/f.yaml) which I just edited in #717, there are "groups" with a single entry, groups without a catch-all at the end, rules with conditions other than the three mentioned in the new docs (e.g. `ruleset`, `verpat`, `category`, etc.)

Perhaps the documentation is meant to describe the current best practices and the files still contain old/deprecated rule specifications? But even so, the discrepancy is likely to confuse people, so perhaps a FIXME comment (or something of the sort) in those lines would help.

**Comment by AMDmi3** [comment]
Yes, existing groups without unclassified rule and `ruleset`/`verpat`/`category` rules are legacy, or some very rare special cases. I don't see any sense in adding a comment to each of these cases.

**Comment by waldyrious** [comment]
Fair enough, but then how about changing "allowed" in

> wwwpart, wwwpat and sourceforge conditions are allowed

to "recommended" or "supported"? That way it doesn't contradict the presence of the legacy rules, which are deprecated but are technically allowed (i.e. the rule parser doesn't ignore or break on them). 

Alternatively, we could add a note like this:

> wwwpart, wwwpat and sourceforge conditions are allowed — other conditions may be found in the files but they are deprecated

WDYT?

**Comment by AMDmi3** [comment]
It's a TL;DR section which is supposed to be as short as possible and describe exactly what should be done, without extra details. It currently lists exactly what should and may be done. People interested to explore ruleset may look into the rest of documentation for details.

**Comment by waldyrious** [comment]
That's fine, but I can't seem to find that clarification (about supported/allowed conditions vs deprecated ones for the split-ambiguities ruleset) in the rest of the documentation either. Am I missing something?

Either way — without making this TL;DR more extensive, WDYT then about the first proposal of replacing "allowed" with "supported"? That way it's a bit less jarring to edit the file and find conditions that are not in the list.

**Comment by AMDmi3** [comment]
> That's fine, but I can't seem to find that clarification (about supported/allowed conditions vs deprecated ones for the split-ambiguities ruleset) in the rest of the documentation either. Am I missing something?

You are not.

> Either way — without making this TL;DR more extensive, WDYT then about the first proposal of replacing "allowed" with "supported"? That way it's a bit less jarring to edit the file and find conditions that are not in the list.

Because it's not allowed, e.g. PR with such rules will not be accepted.

**Comment by waldyrious** [comment]
Ok, got it. I disagree with the outcome but I can see why you'd prefer to have things this way. Thanks for your patience throughout this discussion.

**Pull request merged**
