### PR TITLE
hide the deprecated 1.24.99 release of hledger*

### PR DESCRIPTION
**Pull request by simonmichael**
And any other mistaken release of .99 versions in future.

### CODE REVIEW

**Comment by simonmichael** [comment]
Background: my 1.24.99 release was an error, and is marked deprecated on Hackage.

**Comment by simonmichael** [comment]
My change looks similar to many existing entries, so I'm a little surprised this was needed, but thanks!

When does this go live, eg affecting badge colours at https://repology.org/projects/?search=hledger ?

**Comment by AMDmi3** [comment]
> My change looks similar to many existing entries, so I'm a little surprised this was needed, but thanks!

I've decided to fix it in the parser, to serve as a reminder to add `preferred_versions` support. Also, this way a correct version will be reported for hackage. You change was in fact good apart from that `hledger-lib` should've been `haskell:hledger-lib`.

> When does this go live, eg affecting badge colours at https://repology.org/projects/?search=hledger ?

In a few hours - I've had to also add a rule for stackage which still exposes recalled version so it'll requre another update cycle.

**Comment by simonmichael** [comment]
Wonderful. Thank you for your work, repology.org is fantastic.

**Pull request closed without merging**
