### PR TITLE
Update o.yaml for openkim-models

### PR DESCRIPTION
**Pull request by ellio167**
openkim-models: convert YYYYMMDD to YYYY.MM.DD for consistency.

### CODE REVIEW

**Comment by AMDmi3** [comment]
We don't fix others errors (incorrect version in this case) in Repology. This should be fixed in Debian.

**Comment by ellio167** [comment]
@AMDmi3 I'm confused, there seem to be many examples of this sort of thing in the repo.

`c.yaml:- { name: cmst,                        verpat: "(20[0-9]{2})([0-9]{2})([0-9]{2})",         setver: "$1.$2.$3" } # manjaro`

`t.yaml:- { name: tuxpaint-stamps,             verpat: "(20[0-9]{2})([0-9]{2})([0-9]{2})",         setver: "$1.$2.$3" }`

It seems that the only way to fix this issue in Debian is to increment the `epoch` so that the new version of the package would be `1:2019.03.31`.  Will repology handle this cleanly and identify `1:2019.03.31` as equivalent to `2019.03.31`?

**Comment by AMDmi3** [comment]
> I'm confused, there seem to be many examples of this sort of thing in the repo.

Some are legacy, some are inevitable because of unclear upstream versioning scheme. But the default policy is highlighting problems in repositories instead of masking them.

> Will repology handle this cleanly and identify 1:2019.03.31 as equivalent to 2019.03.31

Sure, dropping epochs and revisions is the first thing repology does when parsing a version.

**Comment by ellio167** [comment]
OK, great.  We'll bump the epoch.  Thanks....

**Pull request closed without merging**
