### PR TITLE
merge veloren-nightly to veloren

### PR DESCRIPTION
**Pull request by Lukas1818**

### CODE REVIEW

**Comment by AMDmi3** [comment]
This belongs to another letter.

**Comment by Lukas1818** [comment]
> This belongs to another letter.

ups sorry
I have fix it now.

**Comment by AMDmi3** [comment]
Please squash into a single commit. Would be nice to fix an extra space before comma along the way.

**Comment by Lukas1818** [comment]
> Please squash into a single commit. Would be nice to fix an extra space before comma along the way.

done

**Pull request merged**
