### PR TITLE
Add rstudio merge rule

### PR DESCRIPTION
**Pull request by pat-s**

### CODE REVIEW

**Comment by AMDmi3** [comment]
- syntax is broken (`]` missing)
- you don't need to merge `-git` and `-bin`, they were already merged with early rules, see https://repology.org/metapackages/?search=rstudio
- merging `-server` is fine, judging by AUR package it comes from the same source repository. It'll need `addflavor: true` flag to indicate that it's a partial package
- `-preview` needs `weak_devel: true` flag to indicate that it should not bump the newest version

**Comment by pat-s** [comment]
Thanks, I tried to adapt the rules to your comment. Still some issues with the preview. Feel free to make the required changes yourself, I'll check out where you placed the flag :)

**Comment by AMDmi3** [comment]
Please fix the syntax

**Comment by AMDmi3** [comment]
Please fix the syntax, it should be `weak_devel`, not `weak-devel`

**Pull request merged**
